### ISSUE TITLE
ibis_parser: Doesn't like io.StringIO + seek with negative values

### ISSUE THREAD

**Issue by Narrat** [Narrat/python3-eispice#1]
> $ python testibis.py
> Traceback (most recent call last):
>   File "testibis.py", line 3, in <module>
>     ibs = eispice.Ibis('test')
>   File "eispice3/module/ibis.py", line 95, in **init**
>     Ibis_Parser.**init**(self, filename, device)
>   File "eispice3/module/ibis_parser.py", line 562, in **init**
>     self.process()
>   File "eispice3/module/ibis_parser.py", line 101, in process
>     if self._process(line) is Done:
>   File "eispice3/module/ibis_parser.py", line 94, in _process
>     return handler(**match.groupdict())
>   File "eispice3/module/ibis_parser.py", line 116, in handleBlock
>     self.fdin.seek(-len(line),1)
> OSError: Can't do nonzero cur-relative seeks

**Comment by Narrat** [comment]
https://stackoverflow.com/questions/19981996/relative-seek-for-io-stringio-in-python3

https://stackoverflow.com/questions/20412518/error-remains-after-running-2to3-py-on-a-module

Strings again

**Comment by Narrat** [comment]
test fixed with https://github.com/Narrat/python3-eispice/commit/49620b72dee7f288489fa2d0866032a5ac29ee82

Still to decide if using binary stuff to check on ibis files would be the better solution
