### ISSUE TITLE
calc: _Result doesn't like dividing anymore

### ISSUE THREAD

**Issue by Narrat** [Narrat/python3-eispice#2]
> File "eispice3/module/calc.py", line 79, in calc.Variable
> Failed example:
>     z = x**x + cos(20*y + x) - (x / (y+50)) # z is of type _Result
> Exception raised:
>     Traceback (most recent call last):
>       File "/usr/lib/python3.4/doctest.py", line 1324, in __run
>         compileflags, 1), test.globs)
>       File "<doctest calc.Variable[3]>", line 1, in <module>
>         z = x**x + cos(20*y + x) - (x / (y+50)) # z is of type _Result
>     TypeError: unsupported operand type(s) for /: 'Variable' and '_Result'

**Comment by Narrat** [comment]
Didn't check what _Result and Variable is yet, but one candidate could be PEP238
https://www.python.org/dev/peps/pep-0238/

**Comment by Narrat** [comment]
In that case all of calc needs to be checked if is one thing defined there that should be // now

**Comment by Narrat** [comment]
Or somewhere is a cast missing
